### ISSUE TITLE
Internal server error in /othersonbs/kml/

### ISSUE THREAD

**Issue by aptiko** [ellak-monades-aristeias/naturebank#2]
Go to http://filotis.itia.ntua.gr/othersonbs/kml/. Result:

```                                                                               
Traceback (most recent call last):                                                                                         
  File "/usr/local/naturebank-virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_
response                                                                                                                   
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/naturebank/naturebank/views.py", line 273, in kml
    arow.kml = '\n'.join([apoly.simplify(tolerance=simplify_fact*meansize, preserve_topology=True).kml for apoly in arow.gi
s_mpoly])
UnboundLocalError: local variable 'meansize' referenced before assignment
```

**Comment by aptiko** [comment]
Same thing in http://filotis.itia.ntua.gr/natura/kml/
